name: ContraLoc
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+13

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0 # Update to the latest version
  firebase_storage: ^12.3.7
  fluttertoast: ^8.2.10
  cupertino_icons: ^1.0.8
  flutter_localization: ^0.3.0
  signature: ^5.5.0
  pdf: ^3.11.1
  photo_view: ^0.15.0
  printing: ^5.13.4
  path_provider: ^2.1.5
  flutter_pdfview: ^1.3.4
  open_filex: ^4.6.0
  shared_preferences: ^2.3.4
  flutter_image_compress: ^2.3.0
  intl: ^0.19.0
  lottie: ^3.3.0
  flutter_spinkit: ^5.2.1
  flutter_colorpicker: ^1.1.0
  flutter_quill: ^10.8.5
  mailer: ^6.3.0
  http: ^1.2.2
  table_calendar: ^3.1.3
  carousel_slider: ^5.0.0
  purchases_flutter: ^8.4.1
  dio: ^5.7.0
  uuid: ^4.5.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
          
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

    - family: DancingScript
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
  assets:
    - assets/icon/LogoContraLoc.png
    - assets/icon/IconContraLoc.png
    - assets/icon/whatsapp_icon.png
    - assets/icon/logoCon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/IconContraLoc.png"
  adaptive_icon_background: "#ffffff" # Couleur de fond pour Android
  adaptive_icon_foreground: "assets/icon/IconContraLoc.png" # Image de premier plan pour Android
  remove_alpha_ios: true
  min_sdk_android: 21